### PR TITLE
Add Inlay Hints

### PR DESCRIPTION
**Pull request by rkk1995**
This adds a color for InlayHints. 

I'm open to changing the color to whatever; just wanted to get general support for it into the Zenburn theme.

Before
image

After
image

### CODE REVIEW

**Comment by rkk1995** [comment]
following up @phha

**Comment by phha** [comment]
Sorry for the delay.

Thanks for taking care of this. Since this is a built-in highlight, would you mind adding it to the core highlight file instead?

**Comment by rkk1995** [comment]
Updated, lmk if you want me to add ` bg` color aswell.

**Comment by phha** [comment]
Merged. Thanks.

**Pull request merged**
